<a href="https://colab.research.google.com/github/natnew/Mini-Python-Projects/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create an empty and a full NumPy array

In [1]:
# python program to create
# Empty and Full Numpy arrays
  
import numpy as np
  
  
# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[94253480287136 94253499637760              8 94253499637760]
 [             8 94253499637760              9              0]
 [94253499638272 94253499638272 94253499638272              0]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [2]:
# python program to create
# Empty and Full Numpy arrays
  
import numpy as np
  
  
# Create an empty array
empa = np.empty([4, 2])
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([4, 3], 95)
print("\n Full Array")
print(flla)

Empty Array
[[4.65674070e-310 3.60739284e-313]
 [2.05833592e-312 4.65674070e-310]
 [0.00000000e+000 0.00000000e+000]
 [9.88131292e-324 0.00000000e+000]]

 Full Array
[[95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]]


In [3]:
# python program to create 
# Empty and Full Numpy arrays
  
import numpy as np
  
# Create an empty array
empa =  np.empty([3,3]) 
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([5,3], 9.9)
print("\n Full Array")
print(flla)

Empty Array
[[2.7e-322 2.7e-322 2.7e-322]
 [2.7e-322 2.7e-322 2.7e-322]
 [2.7e-322 2.7e-322 2.7e-322]]

 Full Array
[[9.9 9.9 9.9]
 [9.9 9.9 9.9]
 [9.9 9.9 9.9]
 [9.9 9.9 9.9]
 [9.9 9.9 9.9]]


# Get the maximum value from given matrix

In [4]:
# import the important module in python
import numpy as np
          
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')
          
# applying matrix.max() method
geeks = gfg.max()
    
print(geeks)

64


In [5]:
# import the important module in python
import numpy as np
          
# make a matrix with numpy
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')
          
# applying matrix.max() method
geeks = gfg.max()
    
print(geeks)

9


# Replace NumPy array elements that doesn’t satisfy the given condition

In [6]:
# Importing Numpy module
import numpy as np
  
# Creating a 1-D Numpy array
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
print("Given array:")
print(n_arr)
  
print("\nReplace all elements of array which are greater than 50. to 15.50")
n_arr[n_arr > 50.] = 15.50
  
print("New array :\n")
print(n_arr)

Given array:
[75.42436315 42.48558583 60.32924763]

Replace all elements of array which are greater than 50. to 15.50
New array :

[15.5        42.48558583 15.5       ]
